[build]
  command = "npm run build"
  publish = "dist"
  functions = "api"

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  external_node_modules = ["stripe"]

[build.environment]
  NODE_VERSION = "18" 